export const IS_OPEN_MODAL = 'REGISTRATION_MODAL';
export const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION';
export const SUCCESS_SUBMIT_SIGN_IN = 'SUCCESS_SUBMIT_SIGN_IN';
export const ERROR_SUBMIT_SIGN_IN = 'ERROR_SUBMIT_SIGN_IN';
