export const SELECT_MASTER = 'SELECT_MASTER';
export const IS_OPEN_SLIDER = 'IS_OPEN_SLIDER';
export const SWITCH_IMAGE_LEFT = 'SWITCH_IMAGE_LEFT';
export const SWITCH_IMAGE_RIGHT = 'SWITCH_IMAGE_RIGHT';
export const VIEW_MORE = 'VIEW_MORE';
