export const IS_OPEN_MODAL = 'REGISTRATION_MODAL';
export const IS_OPEN_IMAGE_MODAL = 'IS_OPEN_IMAGE_MODAL';
export const SWITCH_IMAGE_LEFT = 'SWITCH_IMAGE_LEFT';
export const SWITCH_IMAGE_RIGHT = 'SWITCH_IMAGE_RIGHT';